## Basic Configuration

baseurl = "http://glamcoder.org" 
builddrafts = true
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Georgiy Mogelashvili"
title = "Georgiy Mogelashvili"

theme = "hugo-goa"

## Hugo Built-in Features
## disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
## googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Georgiy Mogelashvili"
intro = "Software Developer, Team Lead"
description = "In his 10+ years experience Georgiy had a chance to work for small local companies, country scale enterprises, non-profit organisations and international corporations.\n\nToday Georgiy is working at Booking.com, world's leading online travel agency. His role there - Senior Developer and Team Lead, and he is responsible for company products development as well as people management.\n\nGeorgiy believes that main skill each manager should have is openness - ability to honestly and fairly talk to your direct reports and people around you in order to achieve results together.\n\nIn his spare time Georgiy likes constructing Lego Technic creations, planespotting in airports around the world, and spending time with his wife and little daughter."
authorimage = "5324.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Georgiy Mogelashvili"
keywords = "mogelashvili,developer,speaker,leader"

## Social Accounts
[params.social]
github = "glamcoder"
instagram = "glamcoder"
## xing = "<username>"
linkedin = "gmogelashvili"
twitter = "glamcoder"
facebook = "glamcoder"
## google = "<username>"
stackoverflow = "2595344"
email = "me@glamcoder.org"

## Extras
[params.extra]
copyright = "© 2018. Georgiy Mogelashvili." 
## poweredby = true
highlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "https://glamcoder.ru"
[[menu.main]]
    name = "speaker"
    identifier = "speaker"
    weight = 200
    url = "/speaker/"
## [[menu.main]]
##     name = "coderag"
##     identifier = "coderag"
##     weight = 300
##     url = "/coderag/"
